FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y \
      python3-protobuf \
      protobuf-compiler \
      libssl-dev \
      build-essential \
      wget \
      libseccomp-dev \
      vim \
      git

RUN wget https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-aarch64.tar.gz -O cmake-linux-aarch64.tar.gz && \
    tar xf cmake-linux-aarch64.tar.gz --strip-components=1 -C /

RUN mkdir -p /work
WORKDIR /work
RUN git config --global --add safe.directory /work

RUN echo $PWD
